image: python:latest

stages:
  - Static Analysis
  - Test
  - Build

pylint:
  stage: Static Analysis
  script:
    - pip install pylint
    - pylint -d C0301,C0116,C0114 src/*.py

pytest:
  stage: Test
  script:
    - pip install pytest
    - cd test/;pytest -v

build:
  image: "tobix/pywine:latest"
  stage: Build
  script:
    - cd src/
    - wine pyinstaller -F main.py
  artifacts:
    paths:
      - src/dist/*.exe
